/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type {GeneratedRoute} from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'application',
    path: '/application',
    component: 'layout.base$view.application',
    meta: {
      title: 'application',
      i18nKey: 'route.application',
      icon: 'mdi:application-cog',
      order: 2
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9
    },
    children: [
      {
        name: 'manage_announcement',
        path: '/manage/announcement',
        component: 'view.manage_announcement',
        meta: {
          title: 'manage_announcement',
          i18nKey: 'route.manage_announcement'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'schedule',
    path: '/schedule',
    component: 'layout.base',
    meta: {
      title: 'schedule',
      i18nKey: 'route.schedule',
      icon: 'mdi:calendar-clock',
      order: 3
    },
    children: [
      {
        name: 'schedule_dispatch',
        path: '/schedule/dispatch',
        component: 'view.schedule_dispatch',
        meta: {
          title: 'schedule_dispatch',
          i18nKey: 'route.schedule_dispatch',
          icon: 'mdi:database-sync-outline',
          order: 3
        }
      },
      {
        name: 'schedule_job',
        path: '/schedule/job',
        component: 'view.schedule_job',
        meta: {
          title: 'schedule_job',
          i18nKey: 'route.schedule_job',
          icon: 'mdi:clipboard-list-outline',
          order: 1
        },
        children: [
          {
            name: 'schedule_job_alarm-events',
            path: '/schedule/job/alarm-events/:jobId',
            component: 'view.schedule_job_alarm-events',
            meta: {
              title: 'schedule_job_alarm-events',
              i18nKey: 'route.schedule_job_alarm-events'
            }
          }
        ]
      },
      {
        name: 'schedule_log',
        path: '/schedule/log',
        component: 'view.schedule_log',
        meta: {
          title: 'schedule_log',
          i18nKey: 'route.schedule_log',
          icon: 'mdi:file-document-multiple-outline',
          order: 2
        }
      }
    ]
  }
];
